In [1]:
import os
import re
import numpy as np
import pandas as pd

In [2]:
path_to_data = '../data/'

embeddings = np.load(path_to_data + 'embeddings.npy')  # (#nodes, 13)
print ('node embeddings shape', embeddings.shape)
df = pd.DataFrame(embeddings)

node embeddings shape (1685895, 13)

In [3]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06,1.685895e+06
mean,5.109737e-01,3.514810e-01,5.798226e-02,7.816976e-02,1.392732e-03,3.663628e+00,-5.753620e-11,8.546143e-02,5.726632e-02,5.430350e-02,3.059858e-02,1.527201e-01,3.057071e-01
std,4.998797e-01,4.774330e-01,2.337100e-01,2.684386e-01,3.729334e-02,2.774695e+00,2.269171e-01,2.795672e-01,2.323509e-01,2.266157e-01,1.722275e-01,3.597176e-01,4.607064e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-7.451090e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,-1.937635e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,9.883900e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e+00,1.278700e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
max,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00,7.142670e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00